FROM node:16-alpine3.14

WORKDIR /usr/src/service-absensi

# RUN set -ex \
#  && cd service-absensi \
#  && npm ci

# RUN set -ex \
#  && cd postgres-database \
#  && npm ci

# RUN set -ex \
#  && npm ci

CMD ["./bootstrap.sh"]
